<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= legacy_e($pageTitle) ?> | Digital Library BI</title><link rel="stylesheet" href="/assets/css/style.css"></head>
<body><header class="site-header"><div class="container navigation"><a class="brand" href="/"><span class="brand-mark">BI</span><span><strong>Digital Library</strong><small>Bank Indonesia Institute</small></span></a><nav class="nav-links"><a href="/">Beranda</a><a href="/catalog">Katalog</a><a href="/e-resources">E-Resources</a></nav></div></header>
<main class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Informasi perpustakaan</p><h1 class="page-heading">News clippings</h1></div><div class="row-actions"><a class="button button-outline" href="/dashboard">← Dashboard</a><a class="button button-outline" href="/">Beranda</a></div></div>
<?php if ($flash): ?><div class="notice notice-<?= legacy_e($flash['type']) ?>"><?= legacy_e($flash['message']) ?></div><?php endif; ?>
<form class="catalog-filters" method="get" action="/news"><input name="q" value="<?= legacy_e($query) ?>" placeholder="Cari judul atau media"><input name="source" value="<?= legacy_e($source) ?>" placeholder="Media sumber"><button class="button button-primary" type="submit">Cari</button></form>
<div class="news-list"><?php foreach ($clippings as $clipping): ?><article class="news-card"><div><p class="eyebrow"><?= legacy_e($clipping['source_media'] ?: 'Sumber tidak dicantumkan') ?></p><h2><?= legacy_e($clipping['title']) ?></h2><p><?= legacy_e($clipping['publish_date'] ? date('d M Y', strtotime($clipping['publish_date'])) : 'Tanggal tidak tersedia') ?></p></div><a class="button button-primary" href="/news/file?id=<?= (int) $clipping['id'] ?>" target="_blank" rel="noopener">Baca clipping ↗</a></article><?php endforeach; ?><?php if ($clippings === []): ?><div class="empty-state"><h2>Belum ada news clipping.</h2><p>Coba kata kunci lain atau kembali lagi nanti.</p></div><?php endif; ?></div>
</div></main></body></html>

