<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= legacy_e($pageTitle) ?> | Digital Library BI</title><link rel="stylesheet" href="/assets/css/style.css"></head>
<body><header class="site-header"><div class="container navigation"><a class="brand" href="/"><span class="brand-mark">BI</span><span><strong>Digital Library</strong><small>Bank Indonesia Institute</small></span></a><nav class="nav-links"><a href="/dashboard">Dashboard</a><a href="/catalog">Katalog</a></nav></div></header>
<main class="section"><div class="container narrow-page"><div class="section-heading"><div><p class="eyebrow">Akuisisi</p><h1 class="page-heading">Usulan koleksi</h1></div><a class="button button-outline" href="/dashboard">Kembali</a></div>
<?php if ($flash): ?><div class="notice notice-<?= legacy_e($flash['type']) ?>"><?= legacy_e($flash['message']) ?></div><?php endif; ?>
<section class="admin-panel"><p class="eyebrow">Kirim usulan baru</p><form class="auth-form" method="post" action="/proposals"><input type="hidden" name="csrf_token" value="<?= legacy_e(legacy_csrf_token()) ?>"><label for="proposal-title">Judul buku</label><input id="proposal-title" name="title" maxlength="255" required><label for="proposal-author">Penulis</label><input id="proposal-author" name="author" maxlength="255"><button class="button button-primary" type="submit">Kirim usulan</button></form></section>
<div class="section-heading dashboard-heading"><h2>Usulan saya</h2></div><div class="admin-list"><?php foreach ($proposals as $proposal): ?><div class="admin-list-row"><div><strong><?= legacy_e($proposal['title']) ?></strong><small><?= legacy_e($proposal['author'] ?: 'Penulis belum dicantumkan') ?> · <?= legacy_e(date('d M Y', strtotime($proposal['created_at']))) ?></small></div><span class="reservation-badge"><?= legacy_e($proposal['status']) ?></span></div><?php endforeach; ?><?php if ($proposals === []): ?><div class="empty-state"><h2>Belum ada usulan.</h2><p>Usulan koleksi Anda akan muncul di sini.</p></div><?php endif; ?></div>
</div></main></body></html>

