<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= legacy_e($pageTitle) ?> | Digital Library BI</title><link rel="stylesheet" href="/assets/css/style.css"></head>
<body><header class="site-header"><div class="container navigation"><a class="brand" href="/"><span class="brand-mark">BI</span><span><strong>Digital Library</strong><small>Bank Indonesia Institute</small></span></a><nav class="nav-links"><a href="/dashboard">Dashboard</a><a href="/admin/news">News</a></nav></div></header>
<main class="section"><div class="container admin-page"><div class="section-heading"><div><p class="eyebrow">Pustakawan</p><h1 class="page-heading">E-Resources</h1></div><a class="button button-outline" href="/dashboard">Kembali</a></div>
<?php if ($flash): ?><div class="notice notice-<?= legacy_e($flash['type']) ?>"><?= legacy_e($flash['message']) ?></div><?php endif; ?>
<section class="admin-panel"><p class="eyebrow">Tambah resource</p><form class="auth-form" method="post" action="/admin/e-resources"><input type="hidden" name="csrf_token" value="<?= legacy_e(legacy_csrf_token()) ?>"><input type="hidden" name="action" value="save"><label for="resource-title">Judul</label><input id="resource-title" name="title" required><label for="resource-url">URL HTTP/HTTPS</label><input id="resource-url" name="url_link" type="url" required><label for="resource-description">Deskripsi</label><textarea id="resource-description" name="description" rows="3"></textarea><button class="button button-primary" type="submit">Tambah resource</button></form></section>
<div class="section-heading dashboard-heading"><h2>Resource terdaftar</h2></div><div class="admin-list"><?php foreach ($resources as $resource): ?><div class="admin-list-row"><div><strong><?= legacy_e($resource['title']) ?></strong><small><?= legacy_e($resource['url_link']) ?> · <?= (int) $resource['click_count'] ?> klik</small></div><form method="post" action="/admin/e-resources"><input type="hidden" name="csrf_token" value="<?= legacy_e(legacy_csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="resource_id" value="<?= (int) $resource['id'] ?>"><button class="button button-text danger-text" type="submit">Hapus</button></form></div><?php endforeach; ?></div>
</div></main></body></html>

