<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= legacy_e($pageTitle) ?> | Digital Library BI</title><link rel="stylesheet" href="/assets/css/style.css"></head>
<body><header class="site-header"><div class="container navigation"><a class="brand" href="/"><span class="brand-mark">BI</span><span><strong>Digital Library</strong><small>Bank Indonesia Institute</small></span></a><nav class="nav-links"><a href="/dashboard">Dashboard</a><a href="/admin/catalog">Katalog</a></nav></div></header>
<main class="section"><div class="container admin-page"><div class="section-heading"><div><p class="eyebrow">Pustakawan</p><h1 class="page-heading">Kelola anggota</h1></div><a class="button button-outline" href="/dashboard">Kembali</a></div>
<?php if ($flash): ?><div class="notice notice-<?= legacy_e($flash['type']) ?>"><?= legacy_e($flash['message']) ?></div><?php endif; ?>
<div class="admin-list"><?php foreach ($members as $member): ?><div class="admin-list-row"><div><strong><?= legacy_e($member['email']) ?></strong><small><?= legacy_e($member['role']) ?><?= $member['nip'] ? ' · NIP ' . legacy_e($member['nip']) : '' ?> · <?= legacy_e(date('d M Y', strtotime($member['created_at']))) ?></small></div><form class="member-status-form" method="post" action="/admin/members"><input type="hidden" name="csrf_token" value="<?= legacy_e(legacy_csrf_token()) ?>"><input type="hidden" name="member_id" value="<?= (int) $member['id'] ?>"><select name="status" aria-label="Status anggota"><option value="pending" <?= $member['status'] === 'pending' ? 'selected' : '' ?>>Pending</option><option value="active" <?= $member['status'] === 'active' ? 'selected' : '' ?>>Aktif</option><option value="inactive" <?= $member['status'] === 'inactive' ? 'selected' : '' ?>>Nonaktif</option></select><button class="button button-text" type="submit">Simpan</button></form></div><?php endforeach; ?></div>
</div></main></body></html>

