<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= legacy_e($pageTitle) ?> | Digital Library BI</title><link rel="stylesheet" href="/assets/css/style.css"></head>
<body><header class="site-header"><div class="container navigation"><a class="brand" href="/"><span class="brand-mark">BI</span><span><strong>Digital Library</strong><small>Bank Indonesia Institute</small></span></a><nav class="nav-links"><a href="/dashboard">Dashboard</a><a href="/admin/catalog">Katalog</a></nav></div></header>
<main class="section"><div class="container admin-page"><div class="section-heading"><div><p class="eyebrow">Pustakawan</p><h1 class="page-heading">News clippings</h1></div><a class="button button-outline" href="/dashboard">Kembali</a></div>
<?php if ($flash): ?><div class="notice notice-<?= legacy_e($flash['type']) ?>"><?= legacy_e($flash['message']) ?></div><?php endif; ?>
<section class="admin-panel"><p class="eyebrow">Upload clipping</p><form class="auth-form" method="post" action="/admin/news" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= legacy_e(legacy_csrf_token()) ?>"><label for="news-title">Judul</label><input id="news-title" name="title" maxlength="255" required><label for="source-media">Media sumber</label><input id="source-media" name="source_media" maxlength="100" required><label for="publish-date">Tanggal terbit</label><input id="publish-date" name="publish_date" type="date" required><label for="clipping-file">File PDF/JPG/PNG</label><input id="clipping-file" name="clipping_file" type="file" accept="application/pdf,image/jpeg,image/png" required><button class="button button-primary" type="submit">Upload clipping</button></form></section>
<div class="section-heading dashboard-heading"><h2>Clipping terunggah</h2></div><div class="admin-list"><?php foreach ($clippings as $clipping): ?><div class="admin-list-row"><div><strong><?= legacy_e($clipping['title']) ?></strong><small><?= legacy_e($clipping['source_media']) ?> · <?= legacy_e($clipping['publish_date']) ?></small></div><a class="button button-text" href="/news/file?id=<?= (int) $clipping['id'] ?>" target="_blank" rel="noopener">Buka</a></div><?php endforeach; ?></div>
</div></main></body></html>

