<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= legacy_e($pageTitle) ?> | Digital Library BI</title><link rel="stylesheet" href="/assets/css/style.css"></head>
<body><header class="site-header"><div class="container navigation"><a class="brand" href="/"><span class="brand-mark">BI</span><span><strong>Digital Library</strong><small>Bank Indonesia Institute</small></span></a><nav class="nav-links"><a href="/dashboard">Dashboard</a><a href="/proposals">Usulan</a></nav></div></header>
<main class="section"><div class="container admin-page"><div class="section-heading"><div><p class="eyebrow">Pustakawan</p><h1 class="page-heading">Tinjau usulan</h1></div><a class="button button-outline" href="/dashboard">Kembali</a></div>
<?php if ($flash): ?><div class="notice notice-<?= legacy_e($flash['type']) ?>"><?= legacy_e($flash['message']) ?></div><?php endif; ?>
<div class="admin-list"><?php foreach ($proposals as $proposal): ?><div class="admin-list-row"><div><strong><?= legacy_e($proposal['title']) ?></strong><small><?= legacy_e($proposal['author'] ?: 'Penulis belum dicantumkan') ?> · <?= legacy_e($proposal['email']) ?> · <?= legacy_e(date('d M Y', strtotime($proposal['created_at']))) ?></small></div><form class="member-status-form" method="post" action="/admin/proposals"><input type="hidden" name="csrf_token" value="<?= legacy_e(legacy_csrf_token()) ?>"><input type="hidden" name="proposal_id" value="<?= (int) $proposal['id'] ?>"><select name="status" aria-label="Status usulan"><option value="submitted" <?= $proposal['status'] === 'submitted' ? 'selected' : '' ?> disabled>Dikirim</option><option value="reviewed" <?= $proposal['status'] === 'reviewed' ? 'selected' : '' ?>>Ditinjau</option><option value="approved" <?= $proposal['status'] === 'approved' ? 'selected' : '' ?>>Disetujui</option><option value="rejected" <?= $proposal['status'] === 'rejected' ? 'selected' : '' ?>>Ditolak</option></select><button class="button button-text" type="submit">Simpan</button></form></div><?php endforeach; ?><?php if ($proposals === []): ?><div class="empty-state"><h2>Belum ada usulan masuk.</h2></div><?php endif; ?></div>
</div></main></body></html>

